task3 baseCommit
savenkoffcom/t1-academy-java-pro pull request #3
Opened 2024-07-01 16:07 UTC by savenkoffcom

2024-07-02 09:32 UTC, Alexandr056 requested changes
нужно поправтиь

2024-07-02 09:32 UTC, Alexandr056 commented on src/main/java/com/savenkoff/study/task3/CustomThreadPool.java
> +        threadPoolExecutor = new ThreadPoolExecutor(
так вы взяли готовую реализацию) просто обернули в свой класс, в задании нужно реализовать свой тред пул, не усложняя и делая просто

2024-07-04 06:07 UTC, savenkoffcom commented on src/main/java/com/savenkoff/study/task3/CustomThreadPool.java
> +        threadPoolExecutor = new ThreadPoolExecutor(
Переписал

2024-07-04 07:14 UTC, Alexandr056 approved these changes
хорошая работа

2024-07-04 07:14 UTC, Alexandr056 commented on src/main/java/com/savenkoff/study/task3/CustomThreadPool.java
> +    private boolean isShutdown;
volatile

2024-07-04 07:14 UTC, Alexandr056 commented on src/main/java/com/savenkoff/study/task3/CustomThreadPool.java
> +    private boolean isTerminate;
volatile

2024-07-04 07:14 UTC, Alexandr056 commented on src/main/java/com/savenkoff/study/task3/CustomThreadPool.java
> +                isTerminate = (blockingQueue.isEmpty()) && (thread.getState() == Thread.State.WAITING);
я бы преложил решение не с проверкой очереди на пустоту, а просто завершить тек задачу и все
p.s. не критично

2024-07-05 06:10 UTC, merged