Task6
savenkoffcom/t1-academy-java-pro pull request #7
Opened 2024-07-26 04:25 UTC by savenkoffcom

@ShumilinAV если будет время - посмотрите один момент - не удалось победить создание бина чтения настроек из application.yml платежного сервиса ExecutorsProperties, вылетает ошибка 
```
2024-07-26T11:23:57.214+07:00  WARN 33672 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'integrations.executors-com.savenkoff.study.task6.configurations.properties.ExecutorsProperties': Could not bind properties to 'ExecutorsProperties' : prefix=integrations.executors, ignoreInvalidFields=false, ignoreUnknownFields=true
```

2024-07-27 08:04 UTC, Alexandr056 requested changes
очень хорошая работа, но есть ряд необходимых правок

2024-07-27 08:04 UTC, Alexandr056 commented on PayService/src/main/java/com/savenkoff/study/task6/controllers/PaymentsController.java
> +    private final RestTemplate restTemplate;
такие интеграции надо вынести на уровень @Service

2024-07-27 08:04 UTC, Alexandr056 commented on PayService/src/main/java/com/savenkoff/study/task6/controllers/PaymentsController.java
> +                "http://localhost:8081/products-app/api/v1/products/debtAccount",
поправте исходя из моего комментария с Properties

2024-07-27 08:04 UTC, Alexandr056 commented on PayService/src/main/java/com/savenkoff/study/task6/configurations/properties/ExecutorsProperties.java
> +@ConfigurationProperties("integrations.executors")
можете еще попробовать собрать параметры в поля через @Value убедится что работает

2024-07-27 08:04 UTC, Alexandr056 commented on PayService/src/main/java/com/savenkoff/study/task6/controllers/ProductsController.java
> +    private final RestTemplate restTemplate;
аналогично предидущему контроллеру

2024-07-27 08:04 UTC, Alexandr056 commented on PayService/src/main/java/com/savenkoff/study/task6/controllers/ProductsController.java
> +    public ResponseEntity<UserProductsDTO> GetUserProducts(@PathVariable("userId") Long userId) {
имя метода с маленькой буквы

2024-07-27 08:04 UTC, Alexandr056 commented on ProductService/src/main/java/com/savenkoff/study/task6/controllers/UsersController.java
> +        return userService.getAll().stream()
это надо вынести в сервис, контроллер не занимается таким, маппинг это операция для сервиса

2024-07-27 08:04 UTC, Alexandr056 commented on ProductService/src/main/java/com/savenkoff/study/task6/entities/Product.java
> +    private User ownerId;
так это owner*ID* или сам Owner?

2024-07-27 08:04 UTC, Alexandr056 commented on ProductService/src/main/java/com/savenkoff/study/task6/repositories/ProductDAO.java
> +public class ProductDAO {
ProductReposotory

2024-07-29 15:40 UTC, savenkoffcom commented on PayService/src/main/java/com/savenkoff/study/task6/configurations/properties/ExecutorsProperties.java
> +@ConfigurationProperties("integrations.executors")
Разобрался, добавил развернутый комментарий в код по этому вопросу.

2024-07-29 16:13 UTC, savenkoffcom commented on ProductService/src/main/java/com/savenkoff/study/task6/repositories/ProductDAO.java
> +public class ProductDAO {
Не соглашусь. Как и в прошлой работе я настаиваю на том, что именовать класс как ProductProperties следует только в случаях использования jpa/jdbc.

2024-07-30 01:41 UTC, savenkoffcom commented on ProductService/src/main/java/com/savenkoff/study/task6/controllers/UsersController.java
> +        return userService.getAll().stream()
перенес

2024-07-30 11:01 UTC, Alexandr056 approved these changes

2024-07-30 11:01 UTC, Alexandr056 commented on ProductService/src/main/java/com/savenkoff/study/task6/repositories/ProductDAO.java
> +public class ProductDAO {
как вам угодно

2024-07-30 11:20 UTC, merged